package com.auction.model;

import java.sql.Timestamp;

public class Item {
    private int itemId;  // The itemId can be auto-generated by the database.
    private int sellerId;
    private String name;
    private String description;
    private double startingPrice;
    private double currentPrice;
    private Timestamp auctionEndTime;
    private String status;

    // Constructor excluding itemId (as it's auto-incremented)
    public Item(int sellerId, String name, String description, double startingPrice, double currentPrice, Timestamp auctionEndTime, String status) {
        this.sellerId = sellerId;
        this.name = name;
        this.description = description;
        this.startingPrice = startingPrice;
        this.currentPrice = currentPrice;
        this.auctionEndTime = auctionEndTime;
        this.status = status;
    }

    // Constructor with itemId, in case you need it when retrieving from DB
    public Item(int itemId, int sellerId, String name, String description, double startingPrice, double currentPrice, Timestamp auctionEndTime, String status) {
        this.itemId = itemId;
        this.sellerId = sellerId;
        this.name = name;
        this.description = description;
        this.startingPrice = startingPrice;
        this.currentPrice = currentPrice;
        this.auctionEndTime = auctionEndTime;
        this.status = status;
    }

    // Getters and Setters
    public int getItemId() {
        return itemId;
    }

    public int getSellerId() {
        return sellerId;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public double getStartingPrice() {
        return startingPrice;
    }

    public double getCurrentPrice() {
        return currentPrice;
    }

    public Timestamp getAuctionEndTime() {
        return auctionEndTime;
    }

    public String getStatus() {
        return status;
    }

    public void setCurrentPrice(double currentPrice) {
        this.currentPrice = currentPrice;
    }
}
